### PR TITLE
Playlist Creation Filtering and Sorting

### LINKED ISSUE #13: FilterPlaylists Submit Functionaltiy
Depends on Issue#12

When yes fetch all playlist items and filter based on bpm and display load/progress screen.

### PR DESCRIPTION
**Pull request by Ykrej**
- Added playlist creation and population api functions
- Added track feature api functions
- Added basic sprintify playlist submission(non-configurable bpm range)

### CODE REVIEW

**Comment by Ykrej** [comment]
@alexthescott I implemented the core functionality for Sprintify but I don't feel like the tempo value for the tracks are very accurate. We may need to make the sort function take into account other values from TrackFeatures to get the gradient we want.

Checkout the [playlist I generated](https://open.spotify.com/playlist/296DHFt2q56h0p4Hq7xvEb?si=4bc03f5b74674841), it doesn't have the feel of a playlist ordered by tempo.

**Comment by alexthescott** [comment]
I git checkout(ed) the branch, and am noticing that the filtered playlists don't adhere to the min and max bpm specified in the popup. Happy to still merge this PR and address that in coming issues!

**Comment by alexthescott** [comment]
The tempo confidence question can be answered [here](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-audio-analysis) however it's a per-track api call which might prohibit it's use in this project idk we'll have to talk about that

**Comment by Ykrej** [comment]
Moved playlist creation logic and api calls into playlistModal. Should be good to merge.

**Review by alexthescott — APPROVED** [review]
👍🏻 beautiful work

**Pull request merged**
