### PR TITLE
Info Page

### LINKED ISSUE #18: Info Page/Modal
Add Info btn to NavBar

Describe What the app is
Describe Spotify API Scopes required
Github Link
Donation Link(s)

Should display as modal on login page
Should display as app view on app page

### PR DESCRIPTION
**Pull request by Ykrej**
- Added Info button to AppNav
- Added Info page to AppNav router
- Added About button to LoginView and Info page in a modal
- Added CD github actions workflow
- Added prettier(Didnt run formatting yet to avoid muddying files changed on the PR)

### CODE REVIEW

**Comment by Ykrej** [comment]
@alexthescott This is what I got right now, I am not sure where to put Github. Any ideas?

image

**Comment by Ykrej** [comment]
Wasn't entirely sure what to put in the description so it is just lorem ipsum for now

**Comment by alexthescott** [comment]
> @alexthescott This is what I got right now, I am not sure where to put Github. Any ideas?
> 
> image
> 

I suppose we could link a GitHub icon below our names? Or we could link it within the paragraph if we mention it there, either way works with me!

**Review by alexthescott — APPROVED** [review]
👨🏻‍💻🤧🫡 stoked on the info page we're 95% there

**Pull request merged**
