### PR TITLE
Info page

### PR DESCRIPTION
**Pull request by alexthescott**
Updated About Page with a lil story + formatting of the Created By, Powered By as a footer
Screen Shot 2023-05-21 at 7 46 53 PM

### CODE REVIEW

**Comment by Ykrej** [comment]
The TLDR is kind of a "What is Sprintify" and the full text is kind of "Why Sprintify". Should we split it into two sections? Cool with going with this or two sections.

**Comment by alexthescott** [comment]
> The TLDR is kind of a "What is Sprintify" and the full text is kind of "Why Sprintify". Should we split it into two sections? Cool with going with this or two sections.

Hmm I wouldn't want a new button in the menu bar, but I think I can imagine appropriate headers for the two sections? I think that the about page looks alright, I'm tempted to find a gif of someone running to put into the very center. The login page will definitely need a "What is Sprintify" explanation

**Review by Ykrej — APPROVED** [review]
I really like the idea of putting the What is Sprintify on the login page.  Ill approve now but feel free to add the What is Sprintify stuff to the PR or make a different one.

**Comment by Ykrej** [comment]
Also I like the idea of a running man gif

**Comment by alexthescott** [comment]
> 

I'll make another PR soon 🤝

**Pull request merged**
