### PR TITLE
Confirmation Flow

### LINKED ISSUE #34: Show In-Progress / Complete Message after BPM Modal
- If needed a loading bar showing current filtered track count? 
- Upon filtering a link to the newly created playlist?

### PR DESCRIPTION
**Pull request by Ykrej**
Added submitting and submitted screens to the SubmissionModal instead of closing on clicking yes. Includes a link to the created playlist as well.

### CODE REVIEW

**Comment by Ykrej** [comment]
Not sure if I should build out the completion modal content more. Like playlist image and larger link. What do you think @alexthescott?

**Comment by alexthescott** [comment]
> Not sure if I should build out the completion modal content more. Like playlist image and larger link. What do you think @alexthescott?

I think that finesse would look good, but I like how it stands now. Fantastic job on the state changing I love what you've done

**Comment by alexthescott** [comment]
My only note is SubmissionState never gets re-assigned to "bpm" after the dialogue, so we sit in the confirmation state until refreshing the page. But that was a super simple fix 😄 I'll merge this and make another PR for you to approve. Great work 🙏🏻

**Review by alexthescott — APPROVED** [review]
🖖🏻

**Review by alexthescott — APPROVED** [review]
🖖🏻

**Pull request merged**
